/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProyectoFinal.GUI;

import ProyectoFinal.BaseDeDatos.UsuarioDAO;
import ProyectoFinal.Hotel.*;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.util.ArrayList;

/**
 *
 * @author Denis Gr
 */
public class Home extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Home.class.getName());

    private int IDusuarioLogueado;
    private String nombreUsuario;
    private ArrayList<String> fotosSimples = new ArrayList<>();
    private ArrayList<String> fotosDoble = new ArrayList<>();
    private ArrayList<String> fotosSuite = new ArrayList<>();

    /**
     * Creates new form Home
     */
    public Home(int id, String nombre) {
        initComponents();
        this.IDusuarioLogueado = id;
        this.nombreUsuario= nombre;
        fotosSimples.clear();
        fotosSimples.add("fotoSimple.jpg");
        fotosSimples.add("fotoSimple2.jpg");
        fotosSimples.add("fotoSimple3.jpg");
        fotosDoble.clear();
        fotosDoble.add("fotosDoble.jpg");
        fotosDoble.add("fotosDoble2.jpg");
        fotosDoble.add("fotosDoble3.jpg");

        fotosSuite.clear();
        fotosSuite.add("fotosSuite.jpg");
        fotosSuite.add("fotosSuite2.jpg");
        fotosSuite.add("fotosSuite3.jpg");

        this.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                escalarFotoPrincipal();

            }
        });
lblPrecioTotal.setOpaque(true);
   lblPrecioTotal.setBackground(new java.awt.Color(255, 153, 51));     
    lblPrecioTotal.setForeground(java.awt.Color.WHITE);    
        
    }

// Crea este método aparte dentro de la clase Home
    private void escalarFotoPrincipal() {
        try {
            // Asegúrate de que el nombre del Label sea el correcto
            int ancho = paisaje.getWidth();
            int alto = paisaje.getHeight();

            if (ancho > 0 && alto > 0) {
                ImageIcon icon = new ImageIcon(getClass().getResource("paisaje.jpg"));
                Image img = icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);
                paisaje.setIcon(new ImageIcon(img));
            }
        } catch (Exception ex) {
            // Silenciamos el error si la imagen aún no carga
        }
        setIconImage(new ImageIcon(getClass().getResource("icono.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fEntrada = new com.toedter.calendar.JDateChooser();
        fSalida = new com.toedter.calendar.JDateChooser();
        SeleccionPersonas = new javax.swing.JComboBox<>();
        SeleccionHabitacion = new javax.swing.JComboBox<>();
        btnVerFotos = new javax.swing.JButton();
        btnReservar = new javax.swing.JButton();
        lblPrecioTotal = new javax.swing.JLabel();
        btnVerReservas = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        paisaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(247, 242, 232));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProyectoFinal/GUI/icono.png"))); // NOI18N
        jPanel1.add(jLabel1);

        fEntrada.setToolTipText("");
        fEntrada.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                fEntradaPropertyChange(evt);
            }
        });
        jPanel1.add(fEntrada);

        fSalida.setToolTipText("");
        fSalida.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                fSalidaPropertyChange(evt);
            }
        });
        jPanel1.add(fSalida);

        SeleccionPersonas.setBackground(new java.awt.Color(255, 153, 51));
        SeleccionPersonas.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        SeleccionPersonas.setForeground(new java.awt.Color(255, 255, 255));
        SeleccionPersonas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Persona", "2 Personas", "3 Personas", "4 Personas" }));
        SeleccionPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionPersonasActionPerformed(evt);
            }
        });
        jPanel1.add(SeleccionPersonas);

        SeleccionHabitacion.setBackground(new java.awt.Color(255, 153, 51));
        SeleccionHabitacion.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        SeleccionHabitacion.setForeground(new java.awt.Color(255, 255, 255));
        SeleccionHabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Habitación Simple", "Habitación Doble", "Habitación Suite" }));
        SeleccionHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionHabitacionActionPerformed(evt);
            }
        });
        jPanel1.add(SeleccionHabitacion);

        btnVerFotos.setBackground(new java.awt.Color(255, 153, 51));
        btnVerFotos.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        btnVerFotos.setForeground(new java.awt.Color(255, 255, 255));
        btnVerFotos.setText("VER FOTOS");
        btnVerFotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerFotosActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerFotos);

        btnReservar.setBackground(new java.awt.Color(255, 153, 51));
        btnReservar.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        btnReservar.setForeground(new java.awt.Color(255, 255, 255));
        btnReservar.setText("RESERVAR");
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });
        jPanel1.add(btnReservar);

        lblPrecioTotal.setBackground(new java.awt.Color(255, 153, 0));
        lblPrecioTotal.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblPrecioTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecioTotal.setText("Precio total: 0.0 €");
        jPanel1.add(lblPrecioTotal);

        btnVerReservas.setBackground(new java.awt.Color(255, 153, 0));
        btnVerReservas.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        btnVerReservas.setForeground(new java.awt.Color(255, 255, 255));
        btnVerReservas.setText("VER RESERVAS");
        btnVerReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerReservasActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerReservas);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(900, 461));
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setLayout(new java.awt.BorderLayout());

        paisaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProyectoFinal/GUI/paisaje.jpg"))); // NOI18N
        jPanel2.add(paisaje, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed

        String seleccion = SeleccionHabitacion.getSelectedItem().toString();
        Habitacion hab = null;
        ArrayList<String> fotosVacias = new ArrayList<>();
        String extras ="";

       if (seleccion.contains("Simple")) {
            hab = new HabitacionSimple(1, 50.0, fotosVacias);
        } else if (seleccion.contains("Doble")) {
            hab = new HabitacionDoble(2, 70.0, fotosVacias);
        } else if(seleccion.contains("Suite")) {
            Suite miSuite  = new Suite(3, 100.0, fotosVacias, true, 20.0, true);
           hab = miSuite;
           extras = "\n  · Incluye Jacuzzi: " + (miSuite.isJacuzzi() ? "Sí" : "No")
           + "\n  · Incluye Minibar: " + (miSuite.isMinibar() ? "Sí" : "No")
           + "\n  · Terraza: " + miSuite.getMetrosterraza() + " metros cuadrados";

        }

        java.util.Date fechaEntrada = fEntrada.getDate();
        java.util.Date fechaSalida = fSalida.getDate();
        java.util.Date fechaHoy = new java.util.Date();

        if (fechaEntrada == null || fechaSalida == null) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione ambas fechas.", "Error", JOptionPane.WARNING_MESSAGE);
            fEntrada.setCalendar(null);
            fSalida.setCalendar(null);
            return;
        }
        if (fechaEntrada.before(fechaHoy)) {

            JOptionPane.showMessageDialog(this, "No puede reservar en una fecha que ya ha pasado", "Fecha no válida", JOptionPane.WARNING_MESSAGE);
            fEntrada.setCalendar(null);
            fSalida.setCalendar(null);
            return;
        }

        if (!fechaSalida.after(fechaEntrada)) {

            JOptionPane.showMessageDialog(this, "La fecha de salida debe ser posterior a la de entrada", "Error en las fechas", JOptionPane.WARNING_MESSAGE);
            fEntrada.setCalendar(null);
            fSalida.setCalendar(null);
            return;
            
            
           

        }
        
        int HabitacionesOcupadas = 0;
        
        java.sql.Date sqlEntrada = new java.sql.Date(fechaEntrada.getTime());
        java.sql.Date sqlSalida = new java.sql.Date(fechaSalida.getTime());
        
        String sqlContar = "SELECT COUNT(*) FROM reservas WHERE tipo = ? AND "
                     + "((fecha_entrada >= ? AND fecha_entrada < ?) OR (fecha_salida > ? AND fecha_salida <= ?) OR (fecha_entrada <= ? AND fecha_salida >= ?))";
        
        try (java.sql.Connection conn = ProyectoFinal.BaseDeDatos.ConexionBBDD.getConexion();
         java.sql.PreparedStatement ps = conn.prepareStatement(sqlContar)) {
        
        ps.setString(1, seleccion); 
        ps.setDate(2, sqlEntrada);
        ps.setDate(3, sqlSalida);
        ps.setDate(4, sqlEntrada);
        ps.setDate(5, sqlSalida);
        ps.setDate(6, sqlEntrada);
        ps.setDate(7, sqlSalida);
        
        try (java.sql.ResultSet rs = ps.executeQuery()) {
            if (rs.next()) {
                HabitacionesOcupadas = rs.getInt(1); 
            }
        }
    } catch (java.sql.SQLException e) {
        System.out.println("Error al comprobar la disponibilidad: " + e.getMessage());
    }


    if (HabitacionesOcupadas >= 10) {
        JOptionPane.showMessageDialog(this, 
            "¡Lo sentímos, ya no hay habitaciones disponibles del tipo '" + seleccion + "' para las fechas seleccionadas!\nActualmente hay " + HabitacionesOcupadas + " ocupadas de 10 disponibles.", 
            "Hotel Completo", 
            JOptionPane.ERROR_MESSAGE);
        return;
    }

        

        long diferenciaEnMilis = Math.abs(fechaSalida.getTime() - fechaEntrada.getTime());
        long dias = diferenciaEnMilis / (1000 * 60 * 60 * 24);
        
        
        double precioPorNoche = hab.getPrecioBase();
double precioTotalCalculado = dias * precioPorNoche;


 
String resumenMsg = "Resumen de tu estancia:\n"
            + "· Tipo: " + seleccion + "\n"
            + "· Duración: " + dias + " noches\n"
            + "· Precio por noche: " + precioPorNoche + " €\n"
            + extras  + "\n"
            + "=======================\n"
            + "PRECIO TOTAL ESTIMADO: " + precioTotalCalculado + " €\n\n"
            + "¿Estás seguro de que deseas confirmar la reserva?";
            
    int confirmar = JOptionPane.showConfirmDialog(this, resumenMsg, "Confirmar Importe de Reserva", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
    if (confirmar == JOptionPane.YES_OPTION) {
        UsuarioDAO dao = new UsuarioDAO();
        
    

        if (dao.guardarReserva(this.IDusuarioLogueado,this.nombreUsuario, fechaEntrada, fechaSalida, SeleccionPersonas.getSelectedItem().toString(), SeleccionHabitacion.getSelectedItem().toString(),precioTotalCalculado)) {
            String mensaje = ("Reserva confirmada para: " + this.nombreUsuario + "\nCoste total de la estancia: " + precioTotalCalculado + "€ ");
            JOptionPane.showMessageDialog(this, mensaje, "Reserva guardada con éxito en nuestra base de datos!", JOptionPane.INFORMATION_MESSAGE);
            fEntrada.setCalendar(null);
            fSalida.setCalendar(null);
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar la reserva en nuestra base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    }//GEN-LAST:event_btnReservarActionPerformed

    private void SeleccionPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionPersonasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeleccionPersonasActionPerformed

    private void SeleccionHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionHabitacionActionPerformed
       
        actualizarPrecio();
        
        
    }//GEN-LAST:event_SeleccionHabitacionActionPerformed

    private void btnVerFotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerFotosActionPerformed

        String seleccion = SeleccionHabitacion.getSelectedItem().toString();
        ArrayList<String> fotosParaMostrar;
        if (seleccion.contains("Simple")) {
            fotosParaMostrar = fotosSimples;

        } else if (seleccion.contains("Doble")) {
            fotosParaMostrar = fotosDoble;
        } else {
            fotosParaMostrar = fotosSuite;
        }
        if (fotosParaMostrar.isEmpty()) {
            System.out.println("No hay fotos disponibles en este momento para esta habitación ");
            return;
        }
        VentanaGaleria ventana = new VentanaGaleria(fotosParaMostrar);
        ventana.setVisible(true);
        ventana.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnVerFotosActionPerformed

    private void btnVerReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerReservasActionPerformed

        TablaReservas tabla = new TablaReservas(this.IDusuarioLogueado);
        tabla.setVisible(true);
        tabla.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        
        
    }//GEN-LAST:event_btnVerReservasActionPerformed

    private void fEntradaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_fEntradaPropertyChange
        
        if ("date".equals(evt.getPropertyName())) {
        actualizarPrecio();
    }
        
        
    }//GEN-LAST:event_fEntradaPropertyChange

    private void fSalidaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_fSalidaPropertyChange
     
        if ("date".equals(evt.getPropertyName())) {
        actualizarPrecio();
    }
        
        
    }//GEN-LAST:event_fSalidaPropertyChange

    private void actualizarPrecio() {
        
        java.util.Date fechaEnt = fEntrada.getDate();
    java.util.Date fechaSal = fSalida.getDate();
    
    if (fechaEnt == null || fechaSal == null) {
        lblPrecioTotal.setText("Precio total: -- €");
        return;
    }
    
    long difMilis = fechaSal.getTime() - fechaEnt.getTime();
    long dias = difMilis / (1000 * 60 * 60 * 24);
    
    if (dias <= 0) {
        lblPrecioTotal.setText("Fecha de salida inválida");
        return;
    }
    
    String seleccion = SeleccionHabitacion.getSelectedItem().toString();
    double precioNoche = 0.0;
    
    if (seleccion.contains("Habitación Simple")) {
        precioNoche = 50.0;
    } else if (seleccion.contains("Habitación Doble")) {
        precioNoche = 70.0;
    } else if (seleccion.contains("Habitación Suite")) {
        precioNoche = 100.0;
    }
    
 double precioTotalCalculado = dias * precioNoche;
    lblPrecioTotal.setText("Precio total: " + precioTotalCalculado + " € (" + dias + " noches)");
}
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {

            new Home(0,"Invitado").setVisible(true);

        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> SeleccionHabitacion;
    private javax.swing.JComboBox<String> SeleccionPersonas;
    private javax.swing.JButton btnReservar;
    private javax.swing.JButton btnVerFotos;
    private javax.swing.JButton btnVerReservas;
    private com.toedter.calendar.JDateChooser fEntrada;
    private com.toedter.calendar.JDateChooser fSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblPrecioTotal;
    private javax.swing.JLabel paisaje;
    // End of variables declaration//GEN-END:variables
}
