/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProyectoFinal.GUI;

import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;

/**
 *
 * @author Denis Gr
 */
public class PantallaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName());

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        getContentPane().setLayout(null);
        getContentPane().setBackground(new java.awt.Color(247, 242, 232));
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setFont(new java.awt.Font("Serif", java.awt.Font.BOLD, 18));
        jLabel1.setForeground(new java.awt.Color(0, 80, 136)); // Azul marino elegante
        jLabel1.setBounds(50, 40, 400, 30);
        
        BtnReservas.setBounds(100, 110, 300, 45);
        BtnReservas.setBackground(new java.awt.Color(255, 153, 51)); 
        BtnReservas.setForeground(java.awt.Color.WHITE);
        BtnReservas.setFont(new java.awt.Font("Tahoma", java.awt.Font.BOLD, 14));
        BtnReservas.setFocusPainted(false);
        
        btnconfigurar.setBounds(100, 180, 300, 45);
        btnconfigurar.setBackground(new java.awt.Color(0, 80, 136)); // Azul marino para diferenciarlo
        btnconfigurar.setForeground(java.awt.Color.WHITE);
        btnconfigurar.setFont(new java.awt.Font("Tahoma", java.awt.Font.BOLD, 14));
        btnconfigurar.setFocusPainted(false);
        
        this.setSize(500, 300);
        this.setResizable(false); 
        this.setLocationRelativeTo(null);
        
                 setIconImage(new ImageIcon(getClass().getResource("/ProyectoFinal/Configuracion/icono.png")).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnconfigurar = new javax.swing.JButton();
        BtnReservas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(147, 142, 132));

        jLabel1.setText("HOLA, BIENVENIDO A LA APLICACIÓN!");

        btnconfigurar.setText(" Configurar");
        btnconfigurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfigurarActionPerformed(evt);
            }
        });

        BtnReservas.setText("Reservas");
        BtnReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReservasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel1)
                .addContainerGap(102, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnconfigurar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnReservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnconfigurar)
                .addGap(18, 18, 18)
                .addComponent(BtnReservas)
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnconfigurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfigurarActionPerformed
        // TODO add your handling code here:
          this.dispose();
                java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    ProyectoFinal.Configuracion.JConfiguracion f = new ProyectoFinal.Configuracion.JConfiguracion();
                    f.cargarValores();
                    f.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
                    f.setVisible(true);
                }
            });
                                         
    }//GEN-LAST:event_btnconfigurarActionPerformed

    private void BtnReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReservasActionPerformed
      
        ProyectoFinal.GUI.TablaReservas tabla = new ProyectoFinal.GUI.TablaReservas(-1); 
    tabla.setVisible(true);

        
        
    }//GEN-LAST:event_BtnReservasActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PantallaPrincipal().setVisible(true));
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnReservas;
    private javax.swing.JButton btnconfigurar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
