/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProyectoFinal.GUI;

import ProyectoFinal.BaseDeDatos.UsuarioDAO;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Denis Gr
 */
public class TablaReservas extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TablaReservas.class.getName());

    private int idCliente;
    private boolean esAdmin;

    /**
     * Creates new form IniciarSesion
     */
    public TablaReservas(int idCliente) {
        initComponents();
        
  this.idCliente = idCliente;
 this.esAdmin = (idCliente == -1);

        if (!ProyectoFinal.BaseDeDatos.ConexionBBDD.estaInicializada()) {
            ProyectoFinal.BaseDeDatos.ConexionBBDD.Inicializar(null);

        }

        cargarDatosTabla();
          configurarVistasPermisos();

        if (this.idCliente == -1) {
            btnEliminar.setVisible(true);
            btnModificar.setVisible(true);
            btnCancelar.setVisible(true);
        } else {
            btnEliminar.setVisible(false);
            btnModificar.setVisible(true);
            btnCancelar.setVisible(true);
        }

        
        setIconImage(new ImageIcon(getClass().getResource("icono.png")).getImage());
        jTable1.setDefaultEditor(Object.class, null);
        jTable1.setBackground(java.awt.Color.WHITE);
        jTable1.setForeground(java.awt.Color.BLACK);
        jTable1.setGridColor(java.awt.Color.LIGHT_GRAY);
        jTable1.setDefaultEditor(Object.class, null);
        
        jPanel1.setLayout(null);
        
        jLabel1.setBounds(30, 50, 300, 300);
        
        btnModificar.setBounds(360, 100, 110, 30);
        btnCancelar.setBounds(360, 150, 110, 30);
        btnEliminar.setBounds(360, 200, 110, 30);
        
       
        
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setRowHeight(30);
        jTable1.getTableHeader().setFont(new java.awt.Font("Serif", java.awt.Font.BOLD, 13));
        jTable1.getTableHeader().setReorderingAllowed(false);
             jScrollPane1.setBounds(500, 40, 700, 500);
        
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(70);  
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(130); 
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(90); 
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(90);  
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(110); 
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(90);  
        jTable1.getColumnModel().getColumn(6).setPreferredWidth(100); 
        
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        
        this.setSize(1250, 650);
        this.setResizable(false); 
        this.setLocationRelativeTo(null); 
        
        try {
            ImageIcon iconoOriginal = (ImageIcon) jLabel1.getIcon();
            if (iconoOriginal != null) {
                Image imagenPura = iconoOriginal.getImage();
                Image imagenEscalada = imagenPura.getScaledInstance(150, 150, Image.SCALE_SMOOTH);
                ImageIcon iconoNítido = new ImageIcon(imagenEscalada);
                jLabel1.setIcon(iconoNítido);
                }
} catch (Exception e) {
    System.out.println("Error al reescalar el logo: " + e.getMessage());
}
            }
        
    
    

    private void cargarDatosTabla() {

        UsuarioDAO dao = new UsuarioDAO();
        DefaultTableModel modelo = dao.obtenerReservasTabla(this.idCliente);
        jTable1.setModel(modelo);
    }

    private void configurarVistasPermisos() {
        if (esAdmin) {
            setTitle("Panel de Control de Reservas - Administrador");
        } else {
            setTitle("Mis Reservas");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnModificar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(247, 242, 232));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProyectoFinal/GUI/LogoHotelLaMancha.png"))); // NOI18N

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setForeground(new java.awt.Color(147, 142, 132));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(btnCancelar))
                            .addComponent(jLabel1)
                            .addComponent(btnModificar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(btnEliminar)))
                .addContainerGap(439, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int filaSel = jTable1.getSelectedRow();

        if (filaSel == -1) {

            JOptionPane.showMessageDialog(this, "Por favor, selecciona una reserva de la lista para eliminar");
            return;

        }

        int idReserva = (int) jTable1.getValueAt(filaSel, 0);

        int respuesta = JOptionPane.showConfirmDialog(this, "Seguro que desea eliminar la reserva Nº " + idReserva + ".\n¿Proceder? ", "Eliminar Reserva", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (respuesta == JOptionPane.YES_OPTION) {

            UsuarioDAO dao = new UsuarioDAO();
            if (dao.eliminarReserva(idReserva)) {
                JOptionPane.showMessageDialog(this, "Reserva eliminada con éxito");
                cargarDatosTabla();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo eliminar la reserva");
            }

        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        int filaSel = jTable1.getSelectedRow();

        if (filaSel == -1) {

            JOptionPane.showMessageDialog(this, "Por favor, selecciona una reserva de la lista para cancelar");
            return;

        }

        int idReserva = (int) jTable1.getValueAt(filaSel, 0);

        int respuesta = JOptionPane.showConfirmDialog(this, "Seguro que desea cancelar la reserva Nº " + idReserva + '?', "Confirmar Cancelación", JOptionPane.YES_NO_OPTION);

        if (respuesta == JOptionPane.YES_OPTION) {

            UsuarioDAO dao = new UsuarioDAO();
            if (dao.CancelarReserva(idReserva)) {
                JOptionPane.showMessageDialog(this, "Reserva cancelada con éxito");
                cargarDatosTabla();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo cancelar la reserva");
            }

        }

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        int filaSel = jTable1.getSelectedRow();

        if (filaSel == -1) {

            JOptionPane.showMessageDialog(this, "Por favor, selecciona una reserva de la lista para modificar");
            return;

        }
        int idReserva = (int) jTable1.getValueAt(filaSel, 0);
        String entradaActual = jTable1.getValueAt(filaSel, 2).toString();
        String salidaActual = jTable1.getValueAt(filaSel, 3).toString();
        String personasActual = jTable1.getValueAt(filaSel, 4).toString();
        String habitacionActual = jTable1.getValueAt(filaSel, 5).toString();

        com.toedter.calendar.JDateChooser jdEntrada = new com.toedter.calendar.JDateChooser();
        com.toedter.calendar.JDateChooser jdSalida = new com.toedter.calendar.JDateChooser();

        String[] opcionesPersonas = {"1 Persona", "2 Personas", "3 Personas", "4 Personas"};
        JComboBox<String> comboPersonas = new JComboBox<>(opcionesPersonas);
        comboPersonas.setSelectedItem(personasActual);

        String[] tiposHabitacion = {"Simple", "Doble", "Suite"};
        JComboBox<String> comboHabitacion = new javax.swing.JComboBox<>(tiposHabitacion);
        comboHabitacion.setSelectedItem(habitacionActual);

        try {
            java.util.Date fechaEnt = java.sql.Date.valueOf(entradaActual);
            java.util.Date fechaSal = java.sql.Date.valueOf(salidaActual);
            jdEntrada.setDate(fechaEnt);
            jdSalida.setDate(fechaSal);

            jdEntrada.setDateFormatString("yyyy-MM-dd");
            jdSalida.setDateFormatString("yyyy-MM-dd");
        } catch (Exception e) {
            System.out.println("Error al cargar fechas en los calendarios: " + e.getMessage());
        }

        JPanel panelEdicion = new JPanel();
        panelEdicion.setLayout(new java.awt.GridLayout(4, 2, 5, 5));

        panelEdicion.add(new JLabel("Fecha Entrada:"));
        panelEdicion.add(jdEntrada);

        panelEdicion.add(new JLabel("Fecha Salida:"));
        panelEdicion.add(jdSalida);

        panelEdicion.add(new JLabel("Número de Personas:"));
        panelEdicion.add(comboPersonas);

        panelEdicion.add(new JLabel("Tipo de Habitación:"));
        panelEdicion.add(comboHabitacion);

        int opcion = JOptionPane.showConfirmDialog(this, panelEdicion,
                "Modificar Reserva Nº " + idReserva, JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        if (opcion == JOptionPane.OK_OPTION) {
            try {
                if (jdEntrada.getDate() == null || jdSalida.getDate() == null) {
                    JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
                    return;
                }

                java.util.Date fEntrada = jdEntrada.getDate();
                java.util.Date fSalida = jdSalida.getDate();

                long difMilis = fSalida.getTime() - fEntrada.getTime();
                long dias = difMilis / (1000 * 60 * 60 * 24);

                if (dias <= 0) {
                    JOptionPane.showMessageDialog(this, "La fecha de salida debe ser posterior a la de entrada.", "Error de fechas", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                String nuevoTipoHab = comboHabitacion.getSelectedItem().toString();
                double precioNoche = 0.0;
                if (nuevoTipoHab.equals("Simple")) {
                    precioNoche = 50.0;
                } else if (nuevoTipoHab.equals("Doble")) {
                    precioNoche = 70.0;
                } else if (nuevoTipoHab.equals("Suite")) {
                    precioNoche = 100.0;
                }

                double nuevoPrecioTotal = dias * precioNoche;

                java.sql.Date nuevaEntrada = new java.sql.Date(fEntrada.getTime());
                java.sql.Date nuevaSalida = new java.sql.Date(fSalida.getTime());

                String numPersonas = comboPersonas.getSelectedItem().toString();

                UsuarioDAO dao = new UsuarioDAO();
                boolean exito = dao.modificarReserva(idReserva, nuevaEntrada, nuevaSalida, numPersonas, nuevoTipoHab, nuevoPrecioTotal);

                if (exito) {
                    JOptionPane.showMessageDialog(this, "Reserva modificada correctamente.");
                    cargarDatosTabla();
                } else {
                    JOptionPane.showMessageDialog(this, "Error al guardar las modificaciones en la Base de Datos.");
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al procesar los datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TablaReservas(-1).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
