/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProyectoFinal.GUI;

import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author Denis Gr
 */
public class VentanaGaleria extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaGaleria.class.getName());

    private ArrayList<String> fotos;
    private int fotoActual = 0;

    /**
     * Creates new form VentanaGaleria
     */
    public VentanaGaleria(ArrayList<String> fotosRecibidas) {
        initComponents();
        this.fotos = fotosRecibidas;
        this.setSize(1000, 750);
        this.setLocationRelativeTo(null);
        this.setResizable(true);
        this.setVisible(true);

        java.awt.EventQueue.invokeLater(() -> mostrarImagenActual());
    }

    public void mostrarImagenActual() {
        if (fotos != null && !fotos.isEmpty() && fotoActual >= 0 && fotoActual < fotos.size()) {
            String ruta = fotos.get(fotoActual);
            java.net.URL imgURL = getClass().getResource(ruta);
            if (imgURL != null) {
                ImageIcon originalIcon = new ImageIcon(imgURL);
                Image img = originalIcon.getImage();

                int panelAncho = jPanel1.getWidth();
                int panelAlto = jPanel1.getHeight();

                if (panelAncho <= 0) {
                    panelAncho = 900;
                }
                if (panelAlto <= 0) {
                    panelAlto = 600;
                }

                int maxAncho = panelAncho - 40;
                int maxAlto = panelAlto - 40;

                int imgAncho = originalIcon.getIconWidth();
                int imgAlto = originalIcon.getIconHeight();

                double ratioImagen = (double) imgAncho / imgAlto;
                double ratioPanel = (double) maxAncho / maxAlto;

                int ancho, alto;
                if (ratioImagen > ratioPanel) {

                    ancho = maxAncho;
                    alto = (int) (maxAncho / ratioImagen);
                } else {

                    alto = maxAlto;
                    ancho = (int) (maxAlto * ratioImagen);
                }

                Image imgEscalada = img.getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);
                labelFotos.setIcon(new ImageIcon(imgEscalada));
                labelFotos.repaint();

                CambioDeFoto.setText("Foto " + (fotoActual + 1) + " de " + fotos.size());

            } else {
                System.out.println("No se encontró el archivo en: " + ruta);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelFotos = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BtnAtras = new javax.swing.JButton();
        CambioDeFoto = new javax.swing.JLabel();
        BtnSiguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 750));
        setPreferredSize(new java.awt.Dimension(1000, 750));

        jPanel1.setBackground(new java.awt.Color(40, 40, 40));

        labelFotos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(labelFotos)
                .addContainerGap(722, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(labelFotos)
                .addContainerGap(345, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(220, 220, 220));
        jPanel2.setMaximumSize(new java.awt.Dimension(800, 80));
        jPanel2.setMinimumSize(new java.awt.Dimension(800, 80));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 80));

        BtnAtras.setText("<");
        BtnAtras.setMaximumSize(new java.awt.Dimension(120, 40));
        BtnAtras.setPreferredSize(new java.awt.Dimension(120, 40));
        BtnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtrasActionPerformed(evt);
            }
        });

        CambioDeFoto.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        CambioDeFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CambioDeFoto.setText("1 de X");
        CambioDeFoto.setMaximumSize(new java.awt.Dimension(200, 50));
        CambioDeFoto.setPreferredSize(new java.awt.Dimension(200, 50));

        BtnSiguiente.setText(">");
        BtnSiguiente.setMaximumSize(new java.awt.Dimension(120, 40));
        BtnSiguiente.setPreferredSize(new java.awt.Dimension(120, 40));
        BtnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(308, 308, 308)
                .addComponent(BtnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(CambioDeFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CambioDeFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtrasActionPerformed

        if (fotos != null && !fotos.isEmpty() && fotoActual > 0) {
            fotoActual--;
            mostrarImagenActual();
        }


    }//GEN-LAST:event_BtnAtrasActionPerformed

    private void BtnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSiguienteActionPerformed

        if (fotos != null && !fotos.isEmpty() && fotoActual < fotos.size() - 1) {
            fotoActual++;
            mostrarImagenActual();
        }

    }//GEN-LAST:event_BtnSiguienteActionPerformed
    public static void main(String[] args) {

    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAtras;
    private javax.swing.JButton BtnSiguiente;
    private javax.swing.JLabel CambioDeFoto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelFotos;
    // End of variables declaration//GEN-END:variables
}
