/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProyectoFinal.Configuracion;

import ProyectoFinal.BaseDeDatos.UsuarioDAO;
import ProyectoFinal.GUI.Home;
import ProyectoFinal.GUI.Starter;
import java.awt.Label;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.*;

/**
 *
 * @author Denis Gr
 */
public class JConfiguracion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JConfiguracion.class.getName());

    /**
     * Creates new form JConfiguracion
     */
    public JConfiguracion() {
        initComponents();
         setIconImage(new ImageIcon(getClass().getResource("/ProyectoFinal/Configuracion/icono.png")).getImage());
         
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        getContentPane().setLayout(null);
getContentPane().setLayout(null);
        getContentPane().setBackground(new java.awt.Color(247, 242, 232));
        
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setFont(new java.awt.Font("Serif", java.awt.Font.BOLD, 16));
        lblTitulo.setBounds(50, 30, 500, 30);
        
        NombreApp.setBounds(80, 90, 150, 25);
        Ip.setBounds(80, 130, 150, 25);
        Puerto.setBounds(80, 170, 150, 25);
        Usuario.setBounds(80, 210, 150, 25);
        Password.setBounds(80, 250, 150, 25);
        
        campoNombreApp.setBounds(240, 90, 250, 25);
        campoIP.setBounds(240, 130, 250, 25);
        campoPuerto.setBounds(240, 170, 250, 25);
        campoUsuario.setBounds(240, 210, 250, 25);
        campoPass.setBounds(240, 250, 250, 25);
        
        btnGuardar.setBounds(225, 310, 150, 35);
        btnGuardar.setBackground(new java.awt.Color(255, 153, 51)); // El naranja corporativo de tu Home
        btnGuardar.setForeground(java.awt.Color.WHITE);
        btnGuardar.setFont(new java.awt.Font("Serif", java.awt.Font.BOLD, 14));
        btnGuardar.setFocusPainted(false);
        
        this.setSize(600, 420);
        this.setResizable(false); 
        this.setLocationRelativeTo(null);
        
    }
    
    public void cargarValores() {
        try {
        GestorConfiguracion gestor = GestorConfiguracion.getInstance();
        Configuracion conf = gestor.cargarConfiguracion();
        
        if(conf != null) {
        
        campoNombreApp.setText(conf.getNombreApp());
        campoIP.setText(conf.getIp_bbdd());
        campoPuerto.setText(conf.getPuerto_bbdd() + "");
        campoUsuario.setText(conf.getUsuario_bbdd());
        campoPass.setText(conf.getContrasena_bbdd());
        }
        }catch(Exception e) {
            System.out.println("ERROR al cargar valores: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NombreApp = new javax.swing.JLabel();
        Ip = new javax.swing.JLabel();
        Puerto = new javax.swing.JLabel();
        Usuario = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        campoNombreApp = new javax.swing.JTextField();
        campoIP = new javax.swing.JTextField();
        campoPuerto = new javax.swing.JTextField();
        campoUsuario = new javax.swing.JTextField();
        campoPass = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NombreApp.setText("Nombre APP:");

        Ip.setText("IP BBDD:");

        Puerto.setText("Puerto BBDD:");

        Usuario.setText("Usuario BBDD:");

        Password.setText("Contraseña BBDD:");

        campoNombreApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreAppActionPerformed(evt);
            }
        });

        campoIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIPActionPerformed(evt);
            }
        });

        lblTitulo.setText("CONFIGURACIÓN BDD");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(200, 200, 200))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ip)
                            .addComponent(NombreApp)
                            .addComponent(Puerto)
                            .addComponent(Usuario)
                            .addComponent(Password))
                        .addGap(251, 251, 251)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoPass, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoNombreApp, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoIP, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(lblTitulo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreApp)
                    .addComponent(campoNombreApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ip)
                    .addComponent(campoIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Puerto)
                    .addComponent(campoPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Usuario)
                    .addComponent(campoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Password)
                    .addComponent(campoPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNombreAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreAppActionPerformed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_campoNombreAppActionPerformed

    private void campoIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIPActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        try {
            String nombreAPP = campoNombreApp.getText();
            String ip = campoIP.getText();
            String puerto = campoPuerto.getText().trim();
            String usuario = campoUsuario.getText();
            String pass = campoPass.getText();

            if(nombreAPP.isEmpty() || ip.isEmpty() || puerto.isEmpty() || usuario.isEmpty() || pass.isEmpty()) {

                JOptionPane.showMessageDialog(this, "Faltan datos por rellenar");
                return;

            }

            Configuracion conf = new Configuracion(nombreAPP,ip,Integer.parseInt(puerto),usuario,pass);
            ProyectoFinal.BaseDeDatos.ConexionBBDD.Inicializar(conf);

            try (java.sql.Connection testCon = ProyectoFinal.BaseDeDatos.ConexionBBDD.getConexion()) {

                GestorConfiguracion gestor = GestorConfiguracion.getInstance();
                gestor.guardarConfiguracion(conf);

                this.dispose();

                Starter.abrirPantallaPrincipal(conf);

            } catch (java.sql.SQLException e) {

                JOptionPane.showMessageDialog(this,  "No se pudo conectar a la Base de Datos con esos datos.\nError: " + e.getMessage(),
                    "Error de Conexión (Acceso Denegado)",  JOptionPane.ERROR_MESSAGE);
            }

            // TODO add your handling code here:
        } catch (Exception ex) {
            System.getLogger(JConfiguracion.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JConfiguracion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ip;
    private javax.swing.JLabel NombreApp;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Puerto;
    private javax.swing.JLabel Usuario;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JTextField campoIP;
    private javax.swing.JTextField campoNombreApp;
    private javax.swing.JTextField campoPass;
    private javax.swing.JTextField campoPuerto;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
